#!/usr/bin/python3

# abolish - for deleting files n stuff

import sys
import os


class Variables:
    program = os.path.basename(sys.argv[0])
    files = []
    args = []
    recursive = False
    force = False
    ignore = False
    splitVars = True
    empty_folder = False
    verbose = False
    success = False
    annoy = False
    less_annoy = False
    delete_empty = False
    verbose_message = ""

    help_message = f"""Usage: {program} [OPTION]... [FILE]...
Remove (unlink) the FILE(s).\n
  -f, --force           ignore nonexistent files and arguments, never prompt
  -i                    prompt before every removal
  -I                    prompt once before removing more than three files, or
                          when removing recursively; less intrusive than -i,
                          while still giving protection against most mistakes
  -r, -R, --recursive   abolish directories and their contents recursively
  -d, --dir             abolish empty directories
      --help        display this help and exit
      --version     output version information and exit\n
By default, abolish does not abolish directories.  Use the --recursive (-r or -R)
option to abolish each listed directory, too, along with all of its contents.\n
To abolish a file whose name starts with a '-', for example '-foo',
use one of these commands:
  {program} -- -foo

  {program} ./-foo

Note that if you use abolish to abolish a file, it might be possible to recover
some of its contents, given sufficient expertise and/or time.  For greater
assurance that the contents are truly unrecoverable, consider using shred(1)."""





class Exceptions(Variables):
    def FileNotFound(self, File):
        print(f"{self.program}: cannot abolish '{File.path}': No such file or directory")

    def IsAFolder(self, File):
        print(f"{self.program}: cannot abolish '{File.path}': Is a directory")

    def MissingOperand(self):
        print(f"{self.program}: missing operand\nTry '{self.program} --help' for more information.")

    def FolderNotEmpty(self, File):
        print(f"{self.program}: cannot abolish '{File.path}': Directory not empty")

    def RefusingToRemove(self, File):
        print(f"{self.program}: refusing to remove '.' or '..' directory: skipping '{File.path}'")



class Path:
    def __init__(self):
        self.path = ""
        self.is_file = False
        self.is_folder = False
        self.is_symlink = False
        self.folder_count = 0
        self.file_count = 0
        self.folders = []

    def get_type(self):
        self.is_file = not os.path.isdir(self.path)
        self.is_folder = os.path.isdir(self.path)
        self.is_symlink = os.path.islink(self.path)


    def abolish(self, Vars, Error):
        self.get_type()

        if Vars.recursive and self.path == "." or self.path == "..":
            Error.RefusingToRemove(self)

        elif not Vars.annoy:
            self.delete(Vars, Error)

        elif self.is_symlink:
            if stdin(f"{Vars.program}: abolish symbolic link '{self.path}'? "):
                self.delete(Vars, Error)

        elif self.is_folder:
            print(self.path)
            exit(1)
            if not Vars.recursive:
                print("sdf")
                Error.IsAFolder(self)
            elif len(os.listdir(self.path)) == 0: # if folder is empty
                if Vars.delete_empty or Vars.recursive:
                    if stdin(f"{Vars.program}: abolish directory '{self.path}'? ").lower().startswith("y"):
                        self.delete(Vars, Error)
            elif Vars.recursive:
                if not len(os.listdir(self.path)) == 0 and self.path not in self.folders: # decend into directory if folder not empty
                    self.folders += [self.path] # dont decend back into a directory if you dont remove everything from that directory
                    if stdin(f"{Vars.program}: decend into directory '{self.path}'? ").lower().startswith("y"):
                        self.delete_folder(Vars, Error)

        elif self.is_file:
            if stdin(f"{Vars.program}: abolish regular file '{self.path}'? ").lower().startswith("y"):
                self.delete(Vars, Error)



    def delete_folder(self, Vars, Error):
        directory = self.path # save path before folder
        for x in os.listdir(self.path): # loop files in folder
            Vars.success = False
            self.path = os.path.join(directory + "/" + x)
            self.abolish(Vars, Error)

        self.path = directory # return to path before the folder
        if len(os.listdir(self.path)) == 0: # delete folder if empty
            Vars.verbose_message = "abolished directory"
            os.rmdir(self.path)



    def delete(self, Vars, Error):
        if self.is_symlink:
            Vars.verbose_message = "abolished"
            os.unlink(self.path)

        elif self.is_file: # files
            Vars.verbose_message = "abolished"
            try:
                os.remove(self.path)
                Vars.success = True
            except FileNotFoundError:
                if not Vars.force:
                    Error.FileNotFound(self)

        elif self.is_folder: # directories
            Vars.verbose_message = "abolished directory"

            if not Vars.recursive and not Vars.delete_empty:
                Error.IsAFolder(self)

            elif len(os.listdir(self.path)) == 0:
                if Vars.delete_empty:
                    os.rmdir(self.path)
                else:
                    Error.FolderNotEmpty(self)

            elif Vars.recursive and self.path not in self.folders: # delete full directories
                self.folders += [self.path]
                self.delete_folder(Vars, Error)
                Vars.success = True


        if Vars.verbose and Vars.success: # print verbose message if file deletion successful
            print(f"{Vars.verbose_message} '{self.path}'")



def stdin(text):
    try:
        return input(text)
    except KeyboardInterrupt:
        exit("")



def get_args(Vars, File, Error):
    for x in sys.argv[1:]:
        if x == "--": # add "--", no longer split vars as they wont be detected as vars after this point
            Vars.args.append(x)
            Vars.splitVars = False
        elif x.startswith("--"): # add long options as one entry
            Vars.args.append(x)
        elif x.startswith("-"): # add combined short options indivdually
            if Vars.splitVars == True:
                for z in list(x):
                    if z != "-": # prevent "-" being added, causes "--" to appear in the arglist
                        Vars.args += [f"-{z}"]
            else: # unless "--" was specified, add it all as one option instead of splitting
                Vars.args += [x]
        else: # add everything else normally
            Vars.args.append(x)


    for x in Vars.args:
        if x.startswith("-") and Vars.ignore == False:
            if x == "--":
                Vars.ignore = True
            if "--help" in x:
                print(Vars.help_message)
                exit(0)
            if "-r" in x.lower() or "--recursive" in x: #recursive '-r'
                Vars.recursive = True
                Vars.delete_empty = True
            if "-f" in x.lower() or "--force" in x:
                Vars.force = True
            if "-d" in x.lower() or "--dir" in x:
                Vars.delete_empty = True
            if "-v" in x.lower() or "--verbose" in x:
                Vars.verbose = True
            if "-i" in x:
                Vars.annoy = True
            if "-I" in x:
                Vars.less_annoy = True
        else:
            x = os.path.join(x)
            if not os.path.isdir(x) or os.path.islink(x):
                File.file_count += 1
            else:
                File.folder_count += 1
            Vars.files.append(x)



def main():
    Vars = Variables()
    Error = Exceptions()
    File = Path()
    get_args(Vars, File, Error)

    if len(sys.argv[1:]) == 0: #exit with no input
        Error.MissingOperand()
        exit(1)

    if Vars.less_annoy and Vars.recursive:
        if not stdin(f"{Vars.program}: abolish {File.folder_count + File.file_count} arguments recursively? ").lower().startswith("y"):
            exit(1)
    elif File.file_count > 3 and Vars.less_annoy:
        if not stdin(f"{Vars.program}: abolish {File.file_count} arguments? ").lower().startswith("y"):
            exit(1)

    for x in Vars.files: # parse files/folders to delete
        Vars.success = False
        File.path = os.path.join(x)
        File.abolish(Vars, Error)



if __name__ == '__main__':
    main()
