#!/usr/bin/python3

# isthatme - print effective userid

import os
import pwd
import sys

program = os.path.basename(sys.argv[0])
help_message = f"""Usage: {program} [OPTION]...
Print the user name associated with the current effective user ID.
Same as id -un.

      --help        display this help and exit
      --version     output version information and exit\n"""
version_message = f"""isthatme (pyutils) 2022.08.02
Written by John Crawford"""

def get_args(): #parse arguments
    for x in sys.argv:
        match x:
            case "--help":
                print(help_message)
                exit(0)
            case "--version":
                print(version_message)
                exit(0)

def main():
    get_args()
    try:
        print(pwd.getpwuid(os.getuid())[0])
    except:
        print(f"cannot find name for user ID {os.getuid()}")

if __name__ == "__main__":
    main()
